version: '3.3'

services:

  sample-app:
    container_name: ${APP_NAME:-sample-app}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./{$APP_NAME}:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development