version: '3.3'

services:

  react:
    container_name: ${APP_NAME:-react-app}
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        APP_NAME: ${APP_NAME}
    volumes:
      - ./${APP_NAME}:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development