version: '2'
services:
    app:
      build:
        context: ./
        dockerfile: app.dockerfile
      working_dir: /var/www
      volumes:
        - ./api/mc_api/:/var/www
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
    api:
        build:
          context: ./
          dockerfile: api.dockerfile
        working_dir: /var/www
        volumes:
          - ./api/mc_api:/var/www
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"
          - "DB_DATABASE=homestead"
          - "DB_USERNAME=homestead"
          - "DB_PASSWORD=secret"
    front-end:
        build:
          context: .
          dockerfile: front-end.dockerfile
        volumes:
          - './myapp:/usr/src/app'  
        ports: 
          - "9000:3000"    
        environment:
          - NODE_ENV=development       
    web:
        build:
          context: ./
          dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
          - api
        ports:
          - 8080:80
    database:
        image: mysql:5.6
        volumes:
          - dbdata:/var/lib/mysql
        environment:
          - "MYSQL_DATABASE=homestead"
          - "MYSQL_USER=homestead"
          - "MYSQL_PASSWORD=secret"
          - "MYSQL_ROOT_PASSWORD=secret"
        # ports:
        #     - "33061:3306"

volumes:
  dbdata:
